{{/*{{- if .Values.build.enabled -}}*/}}

apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ include "springboot.fullname" . }}
  labels:
    {{- include "springboot.labels" . | nindent 4 }}
spec:
  completionDeadlineSeconds: {{ .Values.completionDeadlineSeconds }}
  failedBuildsHistoryLimit: 1
  {{- if .Values.serviceAccount -}}
  serviceAccount: {{ .Values.serviceAccount }}
  {{- end -}}
  {{- if .Values.runPolicy -}}
  runPolicy: {{ .Values.runPolicy | default "serial" }}
  {{- end -}}
  source:
    {{- if .Values.inputType "git" -}}
    type: Git
    git:
      ref: {{ .Values.ref }}
      uri: {{ .Values.uri required "uri value is required "  }}
    contextDir: {{ .Values.contextDir }}
    {{- if .Values.sourceSecret }}
    sourceSecret:
       name: {{ .Values.sourceSecret }}
    {{- end -}}
    {{- else if eq .Values.inputType "docker" -}}
    type: Docker
    dockerfile: {{ .Values.dockerFilePath }}
    {{- end -}}
  strategy:
    {{- if eq .Values.strategyType "s2i-jdk" -}}
    sourceStrategy:
      type: source
      {{- if .Values.build.env -}}
      env: {{- tpl (toYaml .Values.build.env) . | nindent 8 }}
      {{- end -}}
      forcePull: {{ .Values.forcePull }}
      from:
        kind: DockerImage
        name: {{ .Values.strategy.type}}
      {{- if .Values.imagePullSecrets -}}
      pullSecret:
        name: {{ .Values.imagePullSecrets }}
      {{- end -}}
    {{- else if eq .Values.strategy.type "docker" -}}
    dockerStrategy:
      dockerfilePath: {{ .Values.dockerFilePath }}
      nocache: false
      {{- if .Values.imagePullSecrets -}}
      pullSecret: {{ .Values.imagePullSecrets }}
      {{- end -}}
      type: Docker
    {{- end -}}
  output:
    imageLabels:
      {{- include "springboot.selectorLabels" . | nindent 4 }}
      name: app_version
      value: {{ required "tag" .Values.build.image.tag }}
    {{- if .Values.imagePushSecrets -}}
    {{- end -}}
    to:
      kind: DockerImage
      name:
      {{ required "build.image.registry" .Values.build.image.registry }}/{{ required "build.image.name" .Values.build.image.name }}:{{ required "build.image.tag required" .Values.build.image.tag }}
    {{- if and (eq build.output.kind "DockerImage") .Values.imagePushSecrets -}}
    pushSecret: {{ .Values.imagePushSecrets }}
    {{- end -}}

{{/*  {{- end -}}*/}}
